name: chocolatine

env:
  MIRROR_URL: git@github.com:DenizHusson/ChocolatineTest.git

on:
  push:
    branches-ignore:
      - 'ga-ignore-**'
  pull_request:
    types:
      - opened
    branches-ignore:
      - 'ga-ignore-**'

jobs:
  check_coding_style:
    name: "check coding style"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v3
      - name: check
        run: check.sh $(pwd) $(pwd)
  check_program_compilation:
    name: "check program compilation"
    needs: check_coding_style
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v3
      - name: check_make
        run: make
        timeout: 2 minutes
      - name: check_make_fclean
        run: make fclean
  run_tests:
    needs: check_program_compilation
    name: "run test"
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    timeout: 2 minutes
    steps:
      - uses: actions/checkout@v3
      - name: test_run
        run : make tests_run
  push_to_mirror:
    name: "push to mirror"
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}