name: mirroring

env:
  MIRROR_URL: https://github.com/DenizHusson/ChocolatineTest.git

on:
  push:
    branches:
      - main

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            $(MIRROR_URL)
          ssh_private_key:
            ${ secrets.GIT_SSH_PRIVATE_KEY }